client().reducetree('taxi/partitioned*')
client().reducetree('taxi/index*')
client().reducetree('taxi/projections*')
client().reducetree('taxi/raw/projections*')
data = client().reducetree('index*')
data = client().reducetree('taxi/arrays*')
data = client().reducetree('taxi/raw*')
data = client().reducetree('taxi/aggregate*')
data = client().reducetree('taxi/query*')
